language: node_js

node_js:
  - "stable"
  - "8"
  - "7"
  - "6"
  - "4"

script:
  - yarn run lint
  # cover will also run test:jest
  - 'yarn run cover; cat ./coverage/lcov.info | ./node_modules/.bin/coveralls;'
  - yarn run build

cache: yarn
