language: node_js

node_js:
  - "stable"
  - "8"
  - "7"
  - "6"
  - "4"

script:
  - yarn run lint
  # coveralls will run test:jest
  - yarn run coveralls
  - yarn run build

cache: yarn

matrix:
  fast_finish: true